### ISSUE TITLE
Unable to run test data after install

### ISSUE THREAD

**Issue by prm123342** [Oshlack/Slinker#2]
When running the test data after installation I obtain this error (I have both manually set the environment paths and tried via updating the tools.groovy without any luck fixing this). 

(slinker) qbi-paulm:Enviro uqpmars3$ bpipe -p case_sample=$SLINKERDIR/tests/unhealthy_Aligned.sortedByCoord.out.bam -p gene=ETV6 -p genome=19 -p a_mem=20000000000 -p g_mem=20000000000 -p results=$PWD -p threads=4 $SLINKERDIR/workflows/slinker.groovy $SLINKERDIR/tests/*.bam
╒══════════════════════════════════════════════════════════════════════════════════════════════════╕
|                              Starting Pipeline at 2022-01-18 15:03                               |
╘══════════════════════════════════════════════════════════════════════════════════════════════════╛

====================================== Stage make_dir (cases) ======================================
WARNING: An error occurred evaluating your pipeline stage: groovy.lang.MissingPropertyException: No such property: temp_source in stage make_dir. Please see Bpipe log file for full details.
groovy.lang.MissingPropertyException: No such property: temp_source in stage make_dir
at bpipe.PipelineDelegate.propertyMissing(PipelineDelegate.groovy:265)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineDelegate.getProperty(PipelineDelegate.groovy)
at slinker$_run_closure2$_closure17.doCall(slinker.groovy:161)
at slinker$_run_closure2$_closure17.doCall(slinker.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineContext.produceImpl(PipelineContext.groovy:1369)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineContext.invokeMethod(PipelineContext.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineDelegate.methodMissing(PipelineDelegate.groovy:155)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineDelegate.invokeMethod(PipelineDelegate.groovy)
at slinker$_run_closure2.doCall(slinker.groovy:160)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
at bpipe.PipelineStage$_runWrappedBody_closure5.doCall(PipelineStage.groovy:434)
at bpipe.PipelineStage$_runWrappedBody_closure5.doCall(PipelineStage.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:433)
at bpipe.PipelineStage.runBody(PipelineStage.groovy:407)
at bpipe.PipelineStage.run(PipelineStage.groovy:243)
at bpipe.PipelineCategory$_plus_closure5.doCall(PipelineCategory.groovy:227)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
at bpipe.PipelineStage$_runWrappedBody_closure5.doCall(PipelineStage.groovy:434)
at bpipe.PipelineStage$_runWrappedBody_closure5.doCall(PipelineStage.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:433)
at bpipe.PipelineStage.runBody(PipelineStage.groovy:407)
at bpipe.PipelineStage.run(PipelineStage.groovy:243)
at bpipe.PipelineStage$run.call(Unknown Source)
at bpipe.Pipeline.runSegment(Pipeline.groovy:664)
at bpipe.BranchRunner.run(BranchRunner.groovy:69)

=========================================== Bpipe Error ============================================

An error occurred executing your pipeline:

                          No such property: temp_source in stage make_dir                           

Please see the details below for more information.

========================================== Error Details ===========================================

groovy.lang.MissingPropertyException: No such property: temp_source in stage make_dir
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at slinker.groovy$_run_closure2$_closure17.doCall(slinker.groovy:161)
at slinker.groovy$_run_closure2$_closure17.doCall(slinker.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at slinker.groovy$_run_closure2.doCall(slinker.groovy:160)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

====================================================================================================

More details about why this error occurred may be available in the full log file .bpipe/bpipe.log

**Comment by breons** [comment]
Sorry about the delay on this!

The most recent commit resolves this issue. Let me know how you go.
